// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApcp9USWOqiTc-72y9lWrpBDuJ8Fru9to',
    appId: '1:296684319013:web:dc9c8e0064a127e9db6acc',
    messagingSenderId: '296684319013',
    projectId: 'lean-streak-project',
    authDomain: 'lean-streak-project.firebaseapp.com',
    storageBucket: 'lean-streak-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6kEkNTzty4LCtUh3jneHCVxzoUwc8ymM',
    appId: '1:296684319013:android:b4da7fa1822509e4db6acc',
    messagingSenderId: '296684319013',
    projectId: 'lean-streak-project',
    storageBucket: 'lean-streak-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9ws7Q6E7YoXiV2Y2Jc3YUWZ0-xFRX34',
    appId: '1:296684319013:ios:d7d548a522e7dba6db6acc',
    messagingSenderId: '296684319013',
    projectId: 'lean-streak-project',
    storageBucket: 'lean-streak-project.firebasestorage.app',
    iosBundleId: 'com.example.leanStreak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApcp9USWOqiTc-72y9lWrpBDuJ8Fru9to',
    appId: '1:296684319013:web:cfa432a5adf4792cdb6acc',
    messagingSenderId: '296684319013',
    projectId: 'lean-streak-project',
    authDomain: 'lean-streak-project.firebaseapp.com',
    storageBucket: 'lean-streak-project.firebasestorage.app',
  );
}
